import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    categories: [
        { id: 1, name: "All Categories" },
        { id: 2, name: "Home & Lifestyle" },
        { id: 3, name: "Men Fashion" },
        { id: 4, name: "Women Fashion" },
        { id: 5, name: "Electronics" },
        { id: 6, name: "Toys" },
        { id: 7, name: "Beauty & Personal Care" },
        { id: 8, name: "Sports & Outdoors" },
        { id: 9, name: "Health & Wellness" },
        { id: 10, name: "Books & Literature" },
        { id: 11, name: "Automotive" },
        { id: 12, name: "Food & Beverages" },
        { id: 13, name: "Pets & Animals" },
        { id: 14, name: "Arts & Crafts" },
        { id: 15, name: "Travel & Tourism" },
        { id: 16, name: "Education & Learning" },
        { id: 17, name: "Furniture & Decor" },
        { id: 18, name: "Technology & Gadgets" },
        { id: 19, name: "Jewelry & Accessories" },
        { id: 20, name: "Music & Entertainment" },
        { id: 21, name: "Garden & Outdoor Living" },
    ],
    items: [
        {
            id: 1,
            name: "Striped Cotton T-Shirt",
            category: "Men Fashion",
            price: 19.99,
            image: "/shirt.webp",
        },
        {
            id: 2,
            name: "Denim Jacket",
            category: "Men Fashion",
            price: 49.99,
            image: "/shirt.webp",
        },
        {
            id: 3,
            name: "Cotton Polo Shirt",
            category: "Men Fashion",
            price: 29.99,
            image: "/shirt.webp",
        },
        {
            id: 4,
            name: "Slim Fit Jeans",
            category: "Men Fashion",
            price: 39.99,
            image: "/shirt.webp",
        },
        {
            id: 5,
            name: "Printed T-Shirt",
            category: "Men Fashion",
            price: 24.99,
            image: "/shirt.webp",
        },
        {
            id: 6,
            name: "Hooded Sweatshirt",
            category: "Men Fashion",
            price: 34.99,
            image: "/shirt.webp",
        },
        {
            id: 7,
            name: "Maxi Dress",
            category: "Women Fashion",
            price: 59.99,
            image: "/shirt.webp",
        },
        {
            id: 8,
            name: "Leather Jacket",
            category: "Women Fashion",
            price: 79.99,
            image: "/shirt.webp",
        },
        {
            id: 9,
            name: "Floral Print Blouse",
            category: "Women Fashion",
            price: 39.99,
            image: "/shirt.webp",
        },
        {
            id: 10,
            name: "Skinny Jeans",
            category: "Women Fashion",
            price: 49.99,
            image: "/shirt.webp",
        },
        {
            id: 11,
            name: "Wrap Skirt",
            category: "Women Fashion",
            price: 29.99,
            image: "/shirt.webp",
        },
        {
            id: 12,
            name: "Linen Shirt",
            category: "Women Fashion",
            price: 34.99,
            image: "/shirt.webp",
        },
        {
            id: 13,
            name: "Slim Fit Chinos",
            category: "Men Fashion",
            price: 44.99,
            image: "/shirt.webp",
        },
        {
            id: 14,
            name: "Casual Shorts",
            category: "Men Fashion",
            price: 19.99,
            image: "/shirt.webp",
        },
        {
            id: 15,
            name: "Striped Sweater",
            category: "Men Fashion",
            price: 39.99,
            image: "/shirt.webp",
        },
        {
            id: 16,
            name: "Pleated Midi Skirt",
            category: "Women Fashion",
            price: 34.99,
            image: "/shirt.webp",
        },
        {
            id: 17,
            name: "Printed Scarf",
            category: "Women Fashion",
            price: 14.99,
            image: "/shirt.webp",
        },
        {
            id: 18,
            name: "Cropped Trousers",
            category: "Women Fashion",
            price: 29.99,
            image: "/shirt.webp",
        },
        {
            id: 19,
            name: "Checked Shirt",
            category: "Men Fashion",
            price: 34.99,
            image: "/shirt.webp",
        },
        {
            id: 20,
            name: "Trench Coat",
            category: "Women Fashion",
            price: 89.99,
            image: "/shirt.webp",
        },
    ],
};

export const productSlice = createSlice({
    name: "product",
    initialState,
    reducers: {},
});

export const {} = productSlice.actions;

export default productSlice.reducer;
